import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "tutorMo",
  description: "Generated by create next app",
  icons: {
    icon: "/images/tmicon.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add your icon here */}
        <link rel="icon" href="/images/tmicon.png" />
        <title>tutorMo</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true} // Suppress hydration warnings for mismatched attributes
      >
        {children}
      </body>
    </html>
  );
}
